[build]
  publish = ".next"
  command = "pnpm build"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "pnpm dev"
  port = 3000
  publish = ".next"

# Configure to use pnpm instead of npm
[build.processing]
  skip_processing = false

# Ensure we use the correct Node.js version
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"
  PNPM_FLAGS = "--frozen-lockfile=false"

# Configure Next.js settings
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"